B=minecraft:black_concrete
I=minecraft:blue_concrete
P=minecraft:purple_concrete
E=minecraft:green_concrete
N=minecraft:brown_concrete
D=minecraft:gray_concrete
A=minecraft:light_gray_concrete
W=minecraft:white_concrete
R=minecraft:red_concrete
O=minecraft:orange_concrete
Y=minecraft:yellow_concrete
G=minecraft:lime_concrete
U=minecraft:light_blue_concrete
S=minecraft:purple_concrete
K=minecraft:pink_concrete
F=minecraft:white_terracotta
C=minecraft:cyan_concrete
H=minecraft:honey_block
J=minecraft:green_terracotta
L=minecraft:light_gray_concrete
M=minecraft:magenta_concrete
Q=minecraft:light_blue_concrete
T=minecraft:cyan_concrete
V=minecraft:green_concrete
X=minecraft:redstone_block
Z=minecraft:quartz_block
fallback=minecraft:white_concrete minecraft:orange_concrete minecraft:magenta_concrete minecraft:light_blue_concrete minecraft:yellow_concrete minecraft:lime_concrete minecraft:pink_concrete minecraft:cyan_concrete minecraft:purple_concrete minecraft:red_concrete
